export interface ColorVariant {
  name: string;
  hex: string;
  inStock: boolean;
}

export interface Product {
  slug: string;
  name: string;
  brand: string;
  brandSlug: string;
  category: string;
  categorySlug: string;
  /** Extra categories this product also appears in (product_categories join). */
  alsoIn?: string[];
  price: number;
  /** When true, show a WhatsApp inquiry instead of a numeric price/order CTA. */
  priceOnInquiry?: boolean;
  compareAtPrice?: number;
  badge?: string;
  fabricType: string;
  length: string;
  width: string;
  season: string;
  weaveType: string;
  description: string;
  colors: ColorVariant[];
  images: string[];
  isFeatured?: boolean;
  isBestseller?: boolean;

  // Populated from the database, absent in the static seed catalogue below.
  id?: string;
  sku?: string;
  imageAlt?: string;
  isInStock?: boolean;
  stockQuantity?: number;
}

export interface Category {
  name: string;
  slug: string;
  sub: string;
  description: string;
  image: string;
}

export interface Brand {
  name: string;
  slug: string;
  tag: string;
}

/* ── Categories — the 6 from the full client brief ──────────────────────── */

export const categories: Category[] = [
  {
    name: 'Cotton',
    slug: 'cotton',
    sub: 'American Soft · Hard · Imported',
    description:
      'From Hitache to Indicot — 15 cotton lines, breathable and colour-fast, for everyday shalwar kameez.',
    image: '/images/cotton.jpg',
  },
  {
    name: 'Kapra / Wash-n-Wear',
    slug: 'kapra',
    sub: 'Wash & Wear · Summer Suiting',
    description:
      '20 wash & wear lines including PC Kapra, Shaffer Grace and China Tibo — easy-care fabric that keeps its shape.',
    image: '/images/kapra.jpg',
  },
  {
    name: 'Winter Fabric',
    slug: 'winter-fabric',
    sub: 'Wool · Karandi · Khaddar',
    description:
      'Winter King, GNG Wool, Monson and more — warm wool and wool-blend suiting for Peshawar winters.',
    image: '/images/winter-fabric.jpg',
  },
  {
    name: 'Dulha Design',
    slug: 'dulha-design',
    sub: 'Groom · Jamawar · Silk',
    description:
      'Shaffer, Silky Joy and Grace groom pieces — royal jamawar, bowski and half-white fabrics for the big day.',
    image: '/images/dulha-design.jpg',
  },
  {
    name: 'Coat & Waistcoat',
    slug: 'coat-waistcoat',
    sub: 'Imported Suiting · Larkspur',
    description:
      'Larkspur imported worsted from England (75 colours) and Silky Joy waistcoat fabric — tailored formal wear.',
    image: '/images/coat-fabric.jpg',
  },
  {
    name: 'Shawls',
    slug: 'shawls',
    sub: 'Swat Salampur · Bannu · Charsadda',
    description:
      'Authentic Swat Salampur, Bannu, Charsadda and velvet shawls — pure wool warmth with traditional KP styles.',
    image: '/images/shawls.jpg',
  },
];

/* ── Brands — the shortlist implied by the client brief ─────────────────── */

export const brands: Brand[] = [
  { name: 'Grace', slug: 'grace', tag: 'Cotton, Kapra, Winter & Dulha' },
  { name: 'Gul Ahmad', slug: 'gul-ahmad', tag: 'American Soft Cotton & Export KT' },
  { name: 'Hitache', slug: 'hitache', tag: 'Everyday Cotton' },
  { name: 'Sarmad', slug: 'sarmad', tag: 'Hard Cotton' },
  { name: 'Royal Galaxy', slug: 'royal-galaxy', tag: 'Premium Cotton' },
  { name: 'Mir', slug: 'mir', tag: 'Cotton Suits' },
  { name: 'Aymali', slug: 'aymali', tag: 'Cotton, Kapra & Bannu Style' },
  { name: 'Nowroz', slug: 'nowroz', tag: 'Cotton Suits' },
  { name: 'Ababil', slug: 'ababil', tag: 'Cotton Suits' },
  { name: 'Indicot', slug: 'indicot', tag: 'Imported Thai Cotton' },
  { name: 'AJ', slug: 'aj', tag: 'Cotton Suits' },
  { name: 'Gentics', slug: 'gentics', tag: 'Cotton Suits' },
  { name: 'Zain G', slug: 'zain-g', tag: 'Cotton Suits' },
  { name: 'Astoor', slug: 'astoor', tag: 'Cotton + Kapra' },
  { name: 'Shaffer', slug: 'shaffer', tag: 'Wash & Wear and Dulha' },
  { name: 'GNG', slug: 'gng', tag: 'Kapra & Wool' },
  { name: 'Dynasty', slug: 'dynasty', tag: 'Wash & Wear' },
  { name: 'Narkins', slug: 'narkins', tag: '3 Star Wash & Wear' },
  { name: 'Al Misri', slug: 'al-misri', tag: '11 Hazar Wash & Wear' },
  { name: 'China Tibo', slug: 'china-tibo', tag: 'Wash & Wear' },
  { name: 'Japani Bowski', slug: 'japani-bowski', tag: 'Patterned Kapra' },
  { name: 'PC', slug: 'pc', tag: 'Imported Dubai Kapra' },
  { name: 'Faiz International', slug: 'faiz-international', tag: 'Wash & Wear' },
  { name: 'Admani', slug: 'admani', tag: 'Wash & Wear' },
  { name: 'Dauwood', slug: 'dauwood', tag: 'Wash & Wear' },
  { name: 'Rahil', slug: 'rahil', tag: 'Wash & Wear' },
  { name: 'Winter King', slug: 'winter-king', tag: 'Winter Suiting' },
  { name: 'Monson', slug: 'monson', tag: 'Winter Kapra' },
  { name: 'Silky Joy', slug: 'silky-joy', tag: 'Dulha + Coat & Waistcoat' },
  { name: 'Larkspur', slug: 'larkspur', tag: 'Imported England Suiting' },
  { name: 'Swat Salampur', slug: 'swat-salampur', tag: 'Traditional Wool Shawls' },
  { name: 'Bannu', slug: 'bannu', tag: 'Wool Shawls' },
  { name: 'Charsadda', slug: 'charsadda', tag: 'Regional Shawls' },
  { name: 'Velvet', slug: 'velvet', tag: 'Velvet Shawls' },
  { name: 'Bachkana', slug: 'bachkana', tag: 'Traditional Shawls' },
];

/* ── Placeholder galleries — real photos arrive from the client ─────────── */

const COTTON_GALLERY = ['/images/cotton.jpg', '/images/kapra.jpg'];
const KAPRA_GALLERY = ['/images/kapra.jpg', '/images/cotton.jpg'];
const WINTER_GALLERY = ['/images/winter-fabric.jpg', '/images/kapra.jpg', '/images/shawls.jpg'];
const DULHA_GALLERY = ['/images/dulha-design.jpg', '/images/waistcoat-fabric.jpg', '/images/kapra.jpg'];
const COAT_GALLERY = ['/images/coat-fabric.jpg', '/images/waistcoat-fabric.jpg'];
const SHAWL_GALLERY = ['/images/shawls.jpg', '/images/winter-fabric.jpg'];

const SUITING = { length: '4.0 Meters Suit Piece', width: '54 Inches (Bara Bahr)' };
const WINTER_SPEC = { length: '4.5 Meters Suit Piece', width: '54 Inches (Bara Bahr)', season: 'Winter' };
const SHAWL_SPEC = { length: 'Full Size Shawl', width: '54 Inches', season: 'Winter' };

/** "Available in N colours" line — colour NAMES are added by the client later. */
const colorNote = (n?: number) =>
  n ? `\n\nAvailable in ${n} colours — WhatsApp us for the current shades.` : '';

/* ── Products — 55 rows from the full client brief ────────────────────────
   Prices are PLACEHOLDERS (category ranges) until the client's sheet lands.
   colours: [] on purpose — no fake entries; the client adds real colour_variants
   via the admin panel, and category colour filters fall back to WhatsApp. */

export const products: Product[] = [
  // ── Cotton (15) ─────────────────────────────────────────────────────────
  {
    slug: 'hitache-cotton',
    name: 'Hitache Cotton',
    brand: 'Hitache',
    brandSlug: 'hitache',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3499,
    fabricType: 'Hitache Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Hitache cotton — soft hand-feel and colour-fast dyes for daily wear.${colorNote(8)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'gul-ahmad-cotton-american-soft',
    name: 'Gul Ahmad Cotton (American Soft)',
    brand: 'Gul Ahmad',
    brandSlug: 'gul-ahmad',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 4499,
    compareAtPrice: 5499,
    badge: 'Bestseller',
    fabricType: 'American Soft Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Soft Finish',
    description: `Gul Ahmad American Soft — silky smooth cotton with a premium fall.${colorNote(20)}`,
    colors: [],
    images: COTTON_GALLERY,
    isFeatured: true,
    isBestseller: true,
  },
  {
    slug: 'sarmad-cotton-hard',
    name: 'Sarmad Cotton (Hard)',
    brand: 'Sarmad',
    brandSlug: 'sarmad',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3699,
    fabricType: 'Hard Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Tight Weave',
    description: 'Sarmad hard cotton — sturdy weave that holds its shape wash after wash.',
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'royal-galaxy-cotton',
    name: 'Royal Galaxy Cotton',
    brand: 'Royal Galaxy',
    brandSlug: 'royal-galaxy',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3999,
    fabricType: 'Royal Galaxy Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Royal Galaxy cotton — lustrous finish with a smooth drape.${colorNote(12)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'grace-silver-stone-cotton',
    name: 'Grace Silver Stone Cotton',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 4299,
    fabricType: 'Silver Stone Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Textured Plain',
    description: `Grace Silver Stone — subtle stone-textured cotton with a dressy sheen.${colorNote(15)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'mir-cotton',
    name: 'Mir Cotton',
    brand: 'Mir',
    brandSlug: 'mir',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3299,
    fabricType: 'Mir Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Mir cotton — lightweight, breathable everyday suit fabric.${colorNote(12)}`,
    colors: [],
    images: COTTON_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'aymali-cotton',
    name: 'Aymali Cotton',
    brand: 'Aymali',
    brandSlug: 'aymali',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3599,
    fabricType: 'Aymali Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Aymali cotton — combed yarn with a soft, even surface.${colorNote(18)}`,
    colors: [],
    images: COTTON_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'nowroz-cotton',
    name: 'Nowroz Cotton',
    brand: 'Nowroz',
    brandSlug: 'nowroz',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3799,
    fabricType: 'Nowroz Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Nowroz cotton — classic Pakistani summer suiting.${colorNote(18)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'ababil-cotton',
    name: 'Ababil Cotton',
    brand: 'Ababil',
    brandSlug: 'ababil',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3299,
    fabricType: 'Ababil Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Ababil cotton — affordable everyday comfort.${colorNote(8)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'indicot-cotton',
    name: 'Indicot Cotton (Thailand)',
    brand: 'Indicot',
    brandSlug: 'indicot',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 4599,
    badge: 'Imported',
    fabricType: 'Imported Thai Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Indicot — imported from Thailand, extra-long staple with a silky finish.${colorNote(20)}`,
    colors: [],
    images: COTTON_GALLERY,
    isFeatured: true,
  },
  {
    slug: 'aj-cotton',
    name: 'AJ Cotton',
    brand: 'AJ',
    brandSlug: 'aj',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3399,
    fabricType: 'AJ Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `AJ cotton — crisp, easy-to-stitch summer fabric.${colorNote(8)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'gentics-cotton',
    name: 'Gentics Cotton',
    brand: 'Gentics',
    brandSlug: 'gentics',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3599,
    fabricType: 'Gentics Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Gentics cotton — smooth combed cotton for formal and casual wear.${colorNote(13)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'zain-g-cotton',
    name: 'Zain G Cotton',
    brand: 'Zain G',
    brandSlug: 'zain-g',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3799,
    fabricType: 'Zain G Cotton',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Zain G cotton — soft finish with rich, lasting colour.${colorNote(18)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'grace-cotton-mix',
    name: 'Grace Cotton Mix',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Cotton',
    categorySlug: 'cotton',
    price: 3899,
    fabricType: 'Cotton Mix',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Mixed Weave',
    description: `Grace cotton mix — cotton comfort with a blended durability.${colorNote(8)}`,
    colors: [],
    images: COTTON_GALLERY,
  },
  {
    slug: 'astoor',
    name: 'Astoor (Cotton + Kapra)',
    brand: 'Astoor',
    brandSlug: 'astoor',
    category: 'Cotton',
    categorySlug: 'cotton',
    alsoIn: ['kapra'],
    price: 3999,
    fabricType: 'Astoor Cotton-Kapra',
    ...SUITING,
    season: 'All-Season',
    weaveType: 'Fine Plain',
    description: `Astoor — one of the shop's dual-purpose classics, listed under Cotton and Kapra both.${colorNote(20)}`,
    colors: [],
    images: [...COTTON_GALLERY, ...KAPRA_GALLERY.slice(0, 1)],
    isFeatured: true,
  },

  // ── Kapra / Wash-n-Wear (19 + Astoor above) ─────────────────────────────
  {
    slug: 'grace-wash-wear',
    name: 'Grace Wash & Wear (Sada & Design)',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3999,
    fabricType: 'Grace Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Plain & Self-Design',
    description: 'Grace wash & wear — 4 plain (sada) and 3 design options in the shop.',
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'shaffer-grace',
    name: 'Shaffer Grace (Wash-n-Wear)',
    brand: 'Shaffer',
    brandSlug: 'shaffer',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4299,
    fabricType: 'Shaffer Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Shaffer Grace summer wash & wear — easy-care fabric with a soft fall.${colorNote(20)}`,
    colors: [],
    images: KAPRA_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'gng-kapra',
    name: 'GNG',
    brand: 'GNG',
    brandSlug: 'gng',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3699,
    fabricType: 'GNG Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Plain Weave',
    description: `GNG wash & wear — durable daily suiting.${colorNote(12)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'dynasty-kapra',
    name: 'Dynasty',
    brand: 'Dynasty',
    brandSlug: 'dynasty',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4499,
    fabricType: 'Dynasty Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Dynasty wash & wear — formal-grade fabric in limited shades.${colorNote(5)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'grace-swiss',
    name: 'Grace Swiss (Dark Shades)',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4799,
    fabricType: 'Grace Swiss',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Grace Swiss — dark, formal shades for office and events.${colorNote(18)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'narkins-3-star',
    name: 'Narkins 3 Star',
    brand: 'Narkins',
    brandSlug: 'narkins',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4599,
    fabricType: 'Narkins 3 Star Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Narkins 3 Star — premium wash & wear with a smooth finish.${colorNote(18)}`,
    colors: [],
    images: KAPRA_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'al-misri-11-hazar',
    name: 'Al Misri 11 Hazar',
    brand: 'Al Misri',
    brandSlug: 'al-misri',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 5499,
    fabricType: 'Al Misri 11 Hazar',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Al Misri 11 Hazar — fine-count wash & wear with a silky hand.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
    isFeatured: true,
  },
  {
    slug: 'zamzama-grace',
    name: 'Zamzama Grace',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4799,
    fabricType: 'Zamzama Grace Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Zamzama Grace — city-style wash & wear in fashionable shades.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'asko-grace',
    name: 'Asko Grace',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4499,
    fabricType: 'Asko Grace Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Asko Grace — light summer wash & wear.${colorNote(10)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'grace-self-design',
    name: 'Grace Self Design',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4799,
    fabricType: 'Grace Self-Design',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Self-Design',
    description: `Grace self design — tone-on-tone pattern woven into the fabric.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'china-tibo',
    name: 'China Tibo',
    brand: 'China Tibo',
    brandSlug: 'china-tibo',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3899,
    fabricType: 'China Tibo',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Tibo Weave',
    description: `China Tibo — crisp tibo-weave wash & wear.${colorNote(18)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'japani-bowski',
    name: 'Japani Bowski',
    brand: 'Japani Bowski',
    brandSlug: 'japani-bowski',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4999,
    fabricType: 'Japani Bowski',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Bowski',
    description: `Japani bowski — patterned fabric with a dressy finish.${colorNote(12)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'export-kt',
    name: 'Export KT (by Gul Ahmad)',
    brand: 'Gul Ahmad',
    brandSlug: 'gul-ahmad',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4599,
    fabricType: 'Export KT Cotton-Look',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Export KT by Gul Ahmad — export-quality suiting that looks and feels like cotton.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'pc-kapra',
    name: 'PC Kapra (Dubai)',
    brand: 'PC',
    brandSlug: 'pc',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 5999,
    compareAtPrice: 7499,
    badge: 'Imported',
    fabricType: 'PC Imported Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `PC Kapra — imported from Dubai with the widest shade range in the shop.${colorNote(45)}`,
    colors: [],
    images: KAPRA_GALLERY,
    isFeatured: true,
  },
  {
    slug: 'faiz-international',
    name: 'Faiz International Fabrics',
    brand: 'Faiz International',
    brandSlug: 'faiz-international',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3799,
    fabricType: 'Faiz Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Faiz International — cotton-look wash & wear for daily use.${colorNote(11)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'aymali-kapra',
    name: 'Aymali Kapra',
    brand: 'Aymali',
    brandSlug: 'aymali',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3899,
    fabricType: 'Aymali Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Aymali kapra — soft, breathable wash & wear.${colorNote(14)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'admani-wash-wear',
    name: 'Admani (Wash-n-Wear)',
    brand: 'Admani',
    brandSlug: 'admani',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4199,
    fabricType: 'Admani Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Admani wash & wear — smooth finish for summer suits.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'dauwood-fabrics',
    name: 'Dauwood Fabrics',
    brand: 'Dauwood',
    brandSlug: 'dauwood',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 3999,
    fabricType: 'Dauwood Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Dauwood fabrics — reliable daily wash & wear.${colorNote(12)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },
  {
    slug: 'rahil-fabric-international',
    name: 'Rahil Fabric International',
    brand: 'Rahil',
    brandSlug: 'rahil',
    category: 'Kapra / Wash-n-Wear',
    categorySlug: 'kapra',
    price: 4099,
    fabricType: 'Rahil Wash & Wear',
    ...SUITING,
    season: 'Summer',
    weaveType: 'Fine Plain',
    description: `Rahil International — cotton-look suiting with a fine finish.${colorNote(15)}`,
    colors: [],
    images: KAPRA_GALLERY,
  },

  // ── Winter Fabric (5) ───────────────────────────────────────────────────
  {
    slug: 'winter-king',
    name: 'Winter King',
    brand: 'Winter King',
    brandSlug: 'winter-king',
    category: 'Winter Fabric',
    categorySlug: 'winter-fabric',
    price: 6499,
    compareAtPrice: 7999,
    badge: 'Winter 2026',
    fabricType: 'Winter King Wool Blend',
    ...WINTER_SPEC,
    weaveType: 'Winter Weave',
    description: `Winter King — heavy warm suiting, the shop's flagship winter fabric.${colorNote(18)}`,
    colors: [],
    images: WINTER_GALLERY,
    isFeatured: true,
    isBestseller: true,
  },
  {
    slug: 'gng-wool',
    name: 'GNG Wool',
    brand: 'GNG',
    brandSlug: 'gng',
    category: 'Winter Fabric',
    categorySlug: 'winter-fabric',
    price: 5999,
    fabricType: 'GNG Pure Wool',
    ...WINTER_SPEC,
    weaveType: 'Wool Weave',
    description: `GNG wool — pure wool warmth for peak winter.${colorNote(12)}`,
    colors: [],
    images: WINTER_GALLERY,
  },
  {
    slug: 'monson-winter-kapra',
    name: 'Monson (Winter Kapra)',
    brand: 'Monson',
    brandSlug: 'monson',
    category: 'Winter Fabric',
    categorySlug: 'winter-fabric',
    price: 5499,
    fabricType: 'Monson Winter Kapra',
    ...WINTER_SPEC,
    weaveType: 'Winter Weave',
    description: `Monson winter kapra — mid-weight warmth with a soft drape.${colorNote(9)}`,
    colors: [],
    images: WINTER_GALLERY,
  },
  {
    slug: 'grace-winter-design',
    name: 'Grace Design (Winter, Light Shades)',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Winter Fabric',
    categorySlug: 'winter-fabric',
    price: 6299,
    fabricType: 'Grace Winter Design',
    ...WINTER_SPEC,
    weaveType: 'Self-Design',
    description: `Grace winter design — light shades with woven self-patterns.${colorNote(10)}`,
    colors: [],
    images: WINTER_GALLERY,
  },
  {
    slug: 'aymali-bannu-style',
    name: 'Aymali Bannu Style (Wool Kapra)',
    brand: 'Aymali',
    brandSlug: 'aymali',
    category: 'Winter Fabric',
    categorySlug: 'winter-fabric',
    price: 5799,
    fabricType: 'Bannu Style Wool Kapra',
    ...WINTER_SPEC,
    weaveType: 'Bannu Style',
    description: `Aymali Bannu style — traditional KP wool kapra for hard winters.${colorNote(12)}`,
    colors: [],
    images: WINTER_GALLERY,
  },

  // ── Dulha Design (3) ────────────────────────────────────────────────────
  {
    slug: 'shaffer-dulha',
    name: 'Shaffer Dulha Design',
    brand: 'Shaffer',
    brandSlug: 'shaffer',
    category: 'Dulha Design',
    categorySlug: 'dulha-design',
    price: 12999,
    fabricType: 'Shaffer Jamawar & Silk Blend',
    length: '4.5 Meters Suit Piece',
    width: '54 Inches (Bara Bahr)',
    season: 'All-Season',
    weaveType: 'Jamawar',
    description: `Shaffer groom fabric — embroidered jamawar for mehndi and barat.${colorNote(4)}`,
    colors: [],
    images: DULHA_GALLERY,
  },
  {
    slug: 'silky-joy',
    name: 'Silky Joy (Dulha & Coat)',
    brand: 'Silky Joy',
    brandSlug: 'silky-joy',
    category: 'Dulha Design',
    categorySlug: 'dulha-design',
    alsoIn: ['coat-waistcoat'],
    price: 14999,
    fabricType: 'Silky Joy Embroidered',
    length: '4.5 Meters Suit Piece',
    width: '54 Inches (Bara Bahr)',
    season: 'All-Season',
    weaveType: 'Embroidered',
    description: `Silky Joy — embroidered fabric that works for groom suits and waistcoats both.${colorNote(14)}`,
    colors: [],
    images: [...DULHA_GALLERY, ...COAT_GALLERY.slice(0, 1)],
    isFeatured: true,
  },
  {
    slug: 'grace-dulha-suit',
    name: 'Grace Dulha Suit',
    brand: 'Grace',
    brandSlug: 'grace',
    category: 'Dulha Design',
    categorySlug: 'dulha-design',
    price: 15999,
    fabricType: 'Grace Bowski & Half-White Silk',
    length: '4.5 Meters Suit Piece',
    width: '54 Inches (Bara Bahr)',
    season: 'All-Season',
    weaveType: 'Bowski',
    description: 'Grace dulha suit — half-white and bowski pieces for a classic groom look.',
    colors: [],
    images: DULHA_GALLERY,
  },

  // ── Coat & Waistcoat (1 + Silky Joy above) ──────────────────────────────
  {
    slug: 'larkspur',
    name: 'Larkspur (England)',
    brand: 'Larkspur',
    brandSlug: 'larkspur',
    category: 'Coat & Waistcoat',
    categorySlug: 'coat-waistcoat',
    price: 12999,
    compareAtPrice: 15999,
    badge: 'Imported',
    fabricType: 'Imported Worsted Suiting',
    length: '3.5 Meters Suit Piece',
    width: '54 Inches (Bara Bahr)',
    season: 'Winter',
    weaveType: 'Worsted',
    description: `Larkspur imported from England — worsted suiting for coats and waistcoats, the widest shade range in the shop.${colorNote(75)}`,
    colors: [],
    images: COAT_GALLERY,
    isFeatured: true,
    isBestseller: true,
  },

  // ── Shawls (12) ─────────────────────────────────────────────────────────
  {
    slug: 'swat-salampur-72-wool-450g',
    name: 'Swat Salampur 72 Wool (450g)',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 3999,
    fabricType: 'Pure Wool — 72 Wool, 450g',
    ...SHAWL_SPEC,
    weaveType: '72 Wool',
    description: 'Swat Salampur 72 wool shawl, 450g — dense traditional weave from Swat.',
    colors: [],
    images: SHAWL_GALLERY,
    isFeatured: true,
  },
  {
    slug: 'swat-salampur-96-wool-480g',
    name: 'Swat Salampur 96 Wool (480g)',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 4499,
    fabricType: 'Pure Wool — 96 Wool, 480g',
    ...SHAWL_SPEC,
    weaveType: '96 Wool',
    description: 'Swat Salampur 96 wool shawl, 480g — finest count, warmest weight.',
    colors: [],
    images: SHAWL_GALLERY,
    isBestseller: true,
  },
  {
    slug: 'swat-salampur-48-double-wool',
    name: 'Swat Salampur 48 Double Wool',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 3499,
    fabricType: 'Pure Wool — 48 Double Wool',
    ...SHAWL_SPEC,
    weaveType: '48 Double Wool',
    description: 'Swat Salampur 48 double wool shawl — double-ply warmth.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'swat-salampur-48-wool',
    name: 'Swat Salampur 48 Wool',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 2999,
    fabricType: 'Pure Wool — 48 Wool',
    ...SHAWL_SPEC,
    weaveType: '48 Wool',
    description: 'Swat Salampur 48 wool shawl — everyday winter warmth.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'swat-salampur-beri-wala',
    name: 'Swat Salampur Beri Wala (Sharai)',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 2499,
    fabricType: 'Wool — Beri Wala Sharai',
    ...SHAWL_SPEC,
    weaveType: 'Beri Wala',
    description: 'Swat Salampur beri wala shawl (sharai style) — traditional regional weave.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'swat-salampur-52-wool',
    name: 'Swat Salampur 52 Wool',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 3299,
    fabricType: 'Pure Wool — 52 Wool',
    ...SHAWL_SPEC,
    weaveType: '52 Wool',
    description: 'Swat Salampur 52 wool shawl — light-to-mid weight for daily wear.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'swat-salampur-sharai',
    name: 'Swat Salampur Sharai',
    brand: 'Swat Salampur',
    brandSlug: 'swat-salampur',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 1999,
    fabricType: 'Wool — Sharai',
    ...SHAWL_SPEC,
    weaveType: 'Sharai',
    description: 'Swat Salampur sharai shawl — classic style at an easy price.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'bannu-shawl',
    name: 'Bannu Shawl',
    brand: 'Bannu',
    brandSlug: 'bannu',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 4299,
    fabricType: 'Bannu Pure Wool',
    ...SHAWL_SPEC,
    weaveType: 'Bannu Wool',
    description: 'Bannu wool shawl — heavy traditional KP wool, warm through the coldest nights.',
    colors: [],
    images: SHAWL_GALLERY,
    isFeatured: true,
  },
  {
    slug: 'charsadda-shawl-70-30',
    name: 'Charsadda Shawl (70/30)',
    brand: 'Charsadda',
    brandSlug: 'charsadda',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 3499,
    fabricType: 'Wool Blend — 70/30',
    ...SHAWL_SPEC,
    weaveType: '70/30',
    description: 'Charsadda shawl, 70/30 blend — soft hand with a light drape.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'charsadda-shawl-pp',
    name: 'Charsadda Shawl (P.P)',
    brand: 'Charsadda',
    brandSlug: 'charsadda',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 3299,
    fabricType: 'Wool Blend — P.P',
    ...SHAWL_SPEC,
    weaveType: 'P.P',
    description: 'Charsadda P.P shawl — regional favourite with a smooth finish.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'velvet-3-gul-shawl',
    name: 'Velvet (3 Gul)',
    brand: 'Velvet',
    brandSlug: 'velvet',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 4499,
    fabricType: 'Velvet — 3 Gul',
    ...SHAWL_SPEC,
    weaveType: 'Velvet 3 Gul',
    description: 'Velvet 3 gul shawl — rich velvet with traditional gul motifs.',
    colors: [],
    images: SHAWL_GALLERY,
  },
  {
    slug: 'bachkana-shawl',
    name: 'Bachkana Shawl',
    brand: 'Bachkana',
    brandSlug: 'bachkana',
    category: 'Shawls',
    categorySlug: 'shawls',
    price: 2999,
    fabricType: 'Bachkana Wool',
    ...SHAWL_SPEC,
    weaveType: 'Bachkana',
    description: 'Bachkana shawl — lightweight traditional shawl for daily winter use.',
    colors: [],
    images: SHAWL_GALLERY,
  },
];

/* ── Static lookups (fallbacks — storefront pages read from the database) ── */

export function getAllProducts(): Product[] {
  return products;
}

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(
    (p) => p.categorySlug === categorySlug || p.alsoIn?.includes(categorySlug)
  );
}

export function getProductsByBrand(brandSlug: string): Product[] {
  return products.filter((p) => p.brandSlug === brandSlug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getBestsellerProducts(): Product[] {
  return products.filter((p) => p.isBestseller);
}

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getBrand(slug: string): Brand | undefined {
  return brands.find((b) => b.slug === slug);
}
